### Base URL
@baseUrl = http://localhost:3000
@json = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNjZjMjI5Ny0xMDhiLTRjM2EtOTg4Ni1lNTY4ZjQxZDA0MDUiLCJlbWFpbCI6Imp1YW5pdG9AZXhhbXBsZS5jb20iLCJpYXQiOjE3Njk3MDIxOTQsImV4cCI6MTc2OTcwNTc5NH0.MXzGKiloXatEkEerUUXuz-6WVm-PzFbWW5JCV4Aiwow

### Register user
POST {{baseUrl}}/auth/register
Content-Type: {{json}}

{
  "email": "juanito1@example.com",
  "password": "changeme123"
}

### Login user
POST {{baseUrl}}/auth/login
Content-Type: {{json}}

{
  "email": "juanito@example.com",
  "password": "changeme123"
}

### Create note
POST {{baseUrl}}/notes
Content-Type: {{json}}
Authorization: Bearer {{token}}

{
  "title": "My second note",
  "content": "This is a sample note body"
}

### List notes by user
GET {{baseUrl}}/notes
Authorization: Bearer {{token}}

### Archive note
PATCH {{baseUrl}}/notes/618dcf34-7d06-4233-8d76-94c6f412c36f/archive
Authorization: Bearer {{token}}
Content-Type: {{json}}
